name: Polyglot
on: [push]
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew install yarn
      - run: carthage update --platform macos --cache-builds
      - run: yarn install
      - run: yarn build:script
      - run: set -o pipefail && xcodebuild clean build -scheme Polyglot CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
